/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TimeCollection } from "./TimeCollection";

export { TimeCollection__factory } from "./factories/TimeCollection__factory";
